import { useState } from "react";
import { ChevronDown } from "lucide-react";

const FAQS = [
  {
    q: "Is YT Analyzer free to use?",
    a: "Yes, completely free. YT Analyzer is powered by the YouTube Data API v3, which has a generous free quota. You can search channels, view full analytics dashboards, and compare multiple channels at no cost."
  },
  {
    q: "How accurate is the data?",
    a: "All data is pulled directly from the YouTube Data API v3 in real time. Subscriber counts, view counts, likes, and comments reflect what YouTube reports. Engagement rates and analytics metrics are computed from that raw data on our server."
  },
  {
    q: "Why does it only analyze 50 videos?",
    a: "YouTube's Data API uses a quota system (10,000 units/day). Each search costs 100 units and each batch of video details costs 1 unit per video. We cap at 50 videos per channel to stay well within quota limits and keep the tool free for everyone."
  },
  {
    q: "What does the Posting Heatmap show?",
    a: "The heatmap visualizes average views broken down by day of week (rows) and hour of day (columns), based on when each video was published. Darker cells indicate that videos posted at that time historically earn more views. This is based on upload timestamps, not when viewers actually watch — but upload timing does influence initial algorithmic push."
  },
  {
    q: "What is engagement rate and how is it calculated?",
    a: "Engagement rate = (likes + comments) / views × 100. It measures how actively an audience interacts with a video relative to how many people saw it. A rate above 2% is generally considered healthy; above 5% is excellent. Note: YouTube hides exact dislike counts, so those are excluded."
  },
  {
    q: "Can I compare private or unlisted channels?",
    a: "No. YT Analyzer can only access data that YouTube makes publicly available through its API — public channel statistics and public video data. Private videos, unlisted videos, and hidden subscriber counts are not accessible."
  },
  {
    q: "Why does the Compare tool show fewer metrics than the channel dashboard?",
    a: "The comparison loads a summary of each channel (30 videos each) for speed. The full channel dashboard analyzes 50 videos and computes the complete analytics breakdown including heatmap, duration buckets, and individual video scatter data."
  },
  {
    q: "What does the Duration Analysis tell me?",
    a: "It shows which video lengths perform best on a specific channel by grouping videos into duration buckets (e.g., 3–7 min, 7–15 min) and calculating average views and engagement for each group. This helps you identify the optimal video length for that channel's audience — which varies significantly by niche."
  },
  {
    q: "How do the Growth Recommendations work?",
    a: "Recommendations are generated by analyzing the channel's own performance data: the best-performing duration bucket, average engagement rate vs. benchmarks, the highest-performing posting time from the heatmap, and whether outlier videos are skewing the averages. Everything is computed from YouTube API data — no AI guesswork."
  },
  {
    q: "Can I search by YouTube channel ID directly?",
    a: "Yes. The search uses YouTube's search API which accepts channel names, handles (@username), keywords, and direct channel IDs. If you know the exact channel ID, search for it directly for the most precise results."
  },
  {
    q: "Is my search data stored?",
    a: "No. YT Analyzer does not use a database. All data is fetched live from YouTube on each request and discarded when you close the tab. No user accounts, no tracking, no history storage."
  },
  {
    q: "Will the data change if I refresh?",
    a: "Yes — data is fetched live every time. If a channel published a new video or gained subscribers, the updated numbers will appear on your next visit. TanStack Query caches data in your browser session to avoid redundant API calls, but a hard refresh fetches fresh data."
  }
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-border rounded-lg overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 p-5 text-left bg-card hover:bg-muted/50 transition-colors"
        data-testid={`faq-toggle-${q.slice(0, 20)}`}
      >
        <span className="font-medium text-foreground">{q}</span>
        <ChevronDown className={`w-5 h-5 text-muted-foreground flex-shrink-0 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="px-5 pb-5 bg-card">
          <p className="text-muted-foreground leading-relaxed text-sm pt-2 border-t border-border">{a}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  return (
    <div className="max-w-3xl mx-auto py-12 space-y-10">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold tracking-tight">Frequently Asked Questions</h1>
        <p className="text-muted-foreground text-lg">Everything you need to know about YT Analyzer.</p>
      </div>
      <div className="space-y-3">
        {FAQS.map((faq) => (
          <FAQItem key={faq.q} q={faq.q} a={faq.a} />
        ))}
      </div>
      <div className="text-center pt-6 space-y-3">
        <p className="text-muted-foreground">Still have a question?</p>
        <a href="/contact" className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors">
          Contact Us
        </a>
      </div>
    </div>
  );
}
